### ISSUE TITLE
General questions about routing-release

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry-incubator/routing-release#47]
Hi, 
I am note sure if I should have put that on the mailing list, or not, but I will ask the question here. Is there a timeline/roadmap for the routing release to be integrated into the the cf-release, regarding HA Proxy and the PostgreSQL release? Or will it always be a separate release in future?
Does the current version also run with postgres, if I configure it in correctly in the property section? 

```yaml
properties:
  routing_api:
    sqldb:
      host: <IP of SQL Host>
      port: <Port for SQL Host>
      type: mysql
      schema: <Schema name>
      username: <Username for SQL DB>
      password: <Password for SQL DB>
```

Is the manual configuration of the database stable for upgrade in future release?
