### ISSUE TITLE
A problem with the acceptance tests

### ISSUE THREAD

**Issue by georgibarzev** [cloudfoundry-incubator/routing-release#64]
Hi,

Is it possible to run the acceptance tests errand when the CF and Routing deployments are on AWS, not bosh-lite? I'm running routing release 0.143.0 and CF release 250 and the actual TCP routing works as expected, however the acceptance tests bosh errand fails with this:

```
• Failure [3.093 seconds]
Registration
/var/vcap/packages/acceptance_tests/src/code.cloudfoundry.org/routing-acceptance-tests/http_routes/registration_test.go:86
  HTTP Route
  /var/vcap/packages/acceptance_tests/src/code.cloudfoundry.org/routing-acceptance-tests/http_routes/registration_test.go:85
    can register, list, subscribe to sse and unregister routes [It]
    /var/vcap/packages/acceptance_tests/src/code.cloudfoundry.org/routing-acceptance-tests/http_routes/registration_test.go:84

    Expected error:
        <*errors.errorString | 0xc4201d1060>: {
            s: "attempt to read from closed buffer",
        }
        attempt to read from closed buffer
    not to have occurred

Summarizing 1 Failure:

[Fail] Registration HTTP Route [It] can register, list, subscribe to sse and unregister routes
/var/vcap/packages/acceptance_tests/src/code.cloudfoundry.org/routing-acceptance-tests/http_routes/registration_test.go:42

Ran 1 of 1 Specs in 3.098 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 0 Skipped
```

I've redacted the private details, the acceptance tests properties section in the manifest looks like this:

```
  acceptance_tests:
    addresses:
    ----
    cloud_controller:
      admin_password: ---
      admin_user: ---
      api: api.---
      apps_domain: ---
      use_http: false
    skip_ssl_validatio: true
    system_domain: ----
    include_http_routes: true
```

Any clues what I'm doing wrong? Thanks in advance.

Georgi
